# Generated by Django 5.0.3 on 2024-06-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_posts_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='ссылка'),
        ),
    ]
